// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAke8GW21udB17CGO-jqNfg5OissMl5EJo',
    appId: '1:719252956074:web:e00d380446aebb408e01d3',
    messagingSenderId: '719252956074',
    projectId: 'alali-reg-app',
    authDomain: 'alali-reg-app.firebaseapp.com',
    storageBucket: 'alali-reg-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoocSUptlQs2orj3HMvhTAk7vCA8rxavM',
    appId: '1:719252956074:android:f8dbf7d1f66cd73e8e01d3',
    messagingSenderId: '719252956074',
    projectId: 'alali-reg-app',
    storageBucket: 'alali-reg-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzEKsErz6JKPpsRj3wxnNau0U7AlM7ic8',
    appId: '1:719252956074:ios:69de9e52f677ca5a8e01d3',
    messagingSenderId: '719252956074',
    projectId: 'alali-reg-app',
    storageBucket: 'alali-reg-app.appspot.com',
    iosClientId: '719252956074-r9dob1qllk4u6hmt47suqcu6l18g4i5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.regApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzEKsErz6JKPpsRj3wxnNau0U7AlM7ic8',
    appId: '1:719252956074:ios:f3b54e088e132c838e01d3',
    messagingSenderId: '719252956074',
    projectId: 'alali-reg-app',
    storageBucket: 'alali-reg-app.appspot.com',
    iosClientId: '719252956074-gobl74c6lnbfa594ift3dljtjgctvt33.apps.googleusercontent.com',
    iosBundleId: 'com.example.regApp.RunnerTests',
  );
}
